# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev

variables:
- group: my-variable-group

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: '$(Build.Repository.Name):latest'

steps:
- script: |
    echo $(Build.Repository.Name)
    echo $(Build.SourceBranchName)
    echo $(Build.Reason)
    echo $(SONAR_LOGIN)
    echo $(SONAR_PASS)
    echo $(DOCKER_USER)
    echo $(DOCKER_PASS)
    echo $(DOCKER_SERVER)

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
