# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev

pr:
- master
- dev

variables:
- group: my-variable-group
- name: imageName
  value: '$(Build.Repository.Name):latest'

jobs:
- job: build_pr
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  steps:
  - script: |
      git config --global user.email "$(GIT_USER_EMAIL)"
      git config --global user.name "$(GIT_USER_NAME)"
      git checkout $(System.PullRequest.SourceBranch)
      git checkout $(System.PullRequest.TargetBranch)
      git merge $(System.PullRequest.SourceBranch)
      docker build -f Dockerfile -t $(imageName) .

- job: build_branch
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['Build.Reason'], 'IndividualCI')
  steps:
  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'build_branch'

- job: release_branch
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: build_branch
  condition: eq(variables['Build.Reason'], 'IndividualCI')
  steps:
  - script: |
      echo $(Build.Reason)
      echo "=========release_branch========="
    displayName: 'release_branch'

- job: deploy_branch
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: release_branch
  condition: eq(variables['Build.Reason'], 'IndividualCI')
  steps:
  - script: |
      echo $(Build.Reason)
      echo "=========release_branch========="
    displayName: 'deploy_branch'

- job: echo
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      ls -la
      echo "==============="
      git status
      echo "=================="
      git branch
      echo "================="
      echo $(Build.Repository.Name)
      echo $(Build.SourceBranch)
      echo $(Build.SourceBranchName)
      echo $(System.PullRequest.SourceBranch)
      echo $(System.PullRequest.TargetBranch)
      echo $(Build.Reason)
      echo $(SONAR_LOGIN)
      echo $(SONAR_PASS)
      echo $(DOCKER_USER)
      echo $(DOCKER_PASS)
      echo $(DOCKER_SERVER)
      echo "=================="
