# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev

pr:
- master
- dev

variables:
- group: my-variable-group
- name: imageName
  value: '${BUILD_REPOSITORY_NAME##*/}:latest'

jobs:
- job: setvar
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - powershell: |
      timetag=staging-`date +"%Y%m%d-%H-%M"`
      echo "timetag logged - $timetag"
      echo "##vso[task.setvariable variable=timetag;isOutput=true]$timetag"
    displayName: 'set_variable'
  - script: |
      echo "timetag variable is $(set_variable.timetag)"
    displayName: 'get_job_scoped_variable'

- job: get_multi_job_var
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: setvar
  variables:
    timeTag: $[ dependencies.setvar.outputs['set_variable.timetag'] ]
  steps:
  - script: |
      echo "timetag variable is $(timeTag)"
    displayName: 'get_multi_job_variable'
