version: 2.0
jobs:
 build:
   # pre-built images: https://circleci.com/docs/2.0/circleci-images/
   machine: true
   steps:
     - checkout
     - run:
         name: Build
         command: |
           docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_SERVER
           docker build -t $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .
           mkdir -p docker-cache
           docker save -o docker-cache/built-image.tar $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
     - save_cache:
         key: save-image
         paths:
           - docker-cache

 release:
   machine: true
   steps:
     - restore_cache:
         keys:
           - save-image
     - run:
         name: Release
         command: |
           docker load < docker-cache/built-image.tar
           docker tag $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH $DOCKER_SERVER/$CIRCLE_PROJECT_REPONAME:`[ $CIRCLE_BRANCH = 'master' ] && echo 'production' || echo 'staging'`
           docker images
           echo 'Released'

workflows:
 version: 2
 build_release_and_deploy:
   jobs:
     - build
     - release:
         requires:
           - build
         filters:
           branches:
             only:
               - master
               - dev
           
           
