version: 2.0
jobs:
 build:
   # pre-built images: https://circleci.com/docs/2.0/circleci-images/
   machine: true
   steps:
     - checkout
     - run:
         name: Build
         command: |
           docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_SERVER
           docker build -t $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .
     - run:
         name: Release
         command: |
           echo 'Released'
           
           
