version: 2.0
jobs:
 build:
   # pre-built images: https://circleci.com/docs/2.0/circleci-images/
   machine: true
   steps:
     - checkout
     - run:
         name: Build
         command: |
           docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_SERVER
           docker build -t $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .
 release:
   machine: true
   steps:
     - run:
         name: Release
         command: |
           docker tag $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH $DOCKER_SERVER/$CIRCLE_PROJECT_REPONAME:`[ $CIRCLE_BRANCH = 'master' ] && echo 'production' || echo 'staging'`
           echo 'Released'

workflows:
 version: 2
 build_release_and_deploy:
   jobs:
     - build
     - release:
         requires:
           - build
         filters:
           branches:
             only:
               - master
               - dev
           
           
