version: 2.0
jobs:
 build-pr:
   # (pre-built) images: https://circleci.com/docs/2.0/circleci-images/
   machine: true
   steps:
     - checkout
     - run:
         name: Echo var
         command: |
           echo $CIRCLE_PULL_REQUEST

 build-branch:
   # (pre-built) images: https://circleci.com/docs/2.0/circleci-images/
   machine: true
   steps:
     - checkout
     - run:
         name: Build
         command: |
           docker build -t $CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH/\//-} .
           mkdir -p docker-cache
           docker save -o docker-cache/built-image.tar $CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH/\//-}
     - persist_to_workspace:
         root: .
         paths:
           - docker-cache

 release:
   machine: true
   steps:
     - restore_cache:
         keys:
           - save-image
     - run:
         name: Release
         command: |
           docker load < docker-cache/built-image.tar
           docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_SERVER
           if [ "${CIRCLE_BRANCH}" == "dev" ]; then
               docker tag $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH $DOCKER_SERVER/$CIRCLE_PROJECT_REPONAME:staging
               docker push $DOCKER_SERVER/$CIRCLE_PROJECT_REPONAME:staging
           elif [ "${CIRCLE_BRANCH}" == "master" ]; then
               docker tag $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH $DOCKER_SERVER/$CIRCLE_PROJECT_REPONAME:production
               docker push $DOCKER_SERVER/$CIRCLE_PROJECT_REPONAME:production
           fi
           docker images

 deploy:
   machine: true
   steps:
     - run:
         name: Deploy
         command: |
           ssh -o StrictHostKeyChecking=no $STAGING_USER@$STAGING_HOST /home/$STAGING_USER/$SYNC_SCRIPT
           ssh -o StrictHostKeyChecking=no $STAGING_USER@$STAGING_HOST /home/$STAGING_USER/$RELOAD_SCRIPT

workflows:
 version: 2
 build_release_and_deploy:
   jobs:
     - build-pr:
         filters:
           branches:
             ignore:
               - master
               - dev
     - build-branch:
         filters:
           branches:
             only:
               - master
               - dev
     - release-branch:
         requires:
           - build-branch
         filters:
           branches:
             only:
               - master
               - dev
     - deploy-branch:
         requires:
           - release-branch
         filters:
           branches:
             only:
               - master
               - dev

